# Project information
site_name: Pratik Yapay Zeka
site_description: Yapay Zeka'ya pratik bir yaklaşım.
site_author: Abdullah Sahin
site_url: 'https://mrabdullahsahin.github.io/pratik-yapay-zeka/'

# Repository
repo_name: mrabdullahsahin/pratik-yapay-zeka
repo_url: 'https://github.com/mrabdullahsahin/pratik-yapay-zeka'

# Configuration
theme:
  name: 'material'
  language: 'tr'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'