# Project information
site_name: Pratik Yapay Zeka
site_description: Yapay Zeka'ya pratik bir yaklaşım.
site_author: Abdullah Sahin
site_url: 'https://mrabdullahsahin.github.io/pratik-yapay-zeka/'

# Repository
repo_name: mrabdullahsahin/pratik-yapay-zeka
repo_url: 'https://github.com/mrabdullahsahin/pratik-yapay-zeka'

# Copyright
copyright: 'Copyright &copy; 2019 Pratik Yapay Zeka'

# Configuration
theme:
  name: 'material'
  favicon: 'img/logo.png'
  logo: 'img/logo.png'
  language: 'tr'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Page tree
nav:
  - Giriş: index.md
  - Python:
    - Değişkenler: python/degiskenler.md
    - print Fonksiyonu: python/print.md
    - Kaçış Dizileri: python/kacis_dizileri.md
    - Yorum İşareti: python/yorum_isareti.md
    - Kullanıcıdan Bilgi Almak: python/kullanicidan_bilgi_almak.md
    - Koşullu Durumlar: python/kosullu_durumlar.md
    - İşleçler: python/islecler.md
    - Döngüler: python/python_donguler.md
    - Hata Yakalama: python/python_hata_yakalama.md
    - Karakter Dizileri(str): python/python_karakter_dizileri.md
    - Karakter Dizilerinin Metotları: python/python_karakter_dizilerinin_metotlari.md
    - Format Metodu: python/python_format_metodu.md
    - Listeler ve Demetler: python/python_listeler_demetler.md
    - Listeler ve Demetlerin Metodları: python/python_listeler_demetler_metodlari.md
    - Sayılar: python/python_sayilar.md
    - Sözlükler: python/python_sozlukler.md
    - Sözlüklerin Metotları: python/python_sozluklerin_metotlari.md
  - Referanslar: referanslar.md
  - Değişiklik Kaydı: changelog.md

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/mrabdullahsahin'
    - type: 'twitter'
      link: 'https://twitter.com/mrabdullahsahin'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/mrabdullahsahin'