# Project information
site_name: Pratik Yapay Zeka
site_description: Yapay Zeka'ya pratik bir yaklaşım.
site_author: Abdullah Sahin
site_url: 'https://mrabdullahsahin.github.io/pratik-yapay-zeka/'

# Repository
repo_name: mrabdullahsahin/pratik-yapay-zeka
repo_url: 'https://github.com/mrabdullahsahin/pratik-yapay-zeka'

# Copyright
copyright: 'Copyright &copy; 2019 Pratik Yapay Zeka'

# Configuration
theme:
  name: 'material'
  favicon: 'img/logo.png'
  logo: 'img/logo.png'
  language: 'tr'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Page tree
nav:
  - Giriş: index.md
  - Python:
    - Değişkenler: python/degiskenler.md
  - Değişiklik Kaydı: changelog.md

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/mrabdullahsahin'
    - type: 'twitter'
      link: 'https://twitter.com/mrabdullahsahin'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/mrabdullahsahin'